blueprint:
  name: Allereinfachster Blueprint
  description: "Schaltet eine Lampe zur angegebenen Uhrzeit ein."
  domain: automation
  input:
    trigger_time:
      name: Uhrzeit
      selector:
        time: {}
    light_target:
      name: Ziel-Licht
      selector:
        entity:
          domain: light

trigger:
  - platform: time
    at: !input trigger_time

action:
  - service: light.turn_on
    target:
      entity_id: !input light_target

mode: single
